[lint]

select = [
    "E",     # pycodestyle (Error)
    "W",     # pycodestyle (Warning)
    "F",     # pyflakes
    "ASYNC", # flake8-async
    "S",     # flake8-bandit
    "UP",    # pyupgrade
    "PL",    # pylint
    "TID",   # flake8-tidy-imports
    "N",     # pep8-naming
    "B",     # flake8-bugbear
    "A",     # flake8-builtins
    "SLF",   # flake8-self
    "T20",   # flake8-print
    "RUF",   # ruff (RUFF specific rules)
    "Q",     # flake8-quotes
    "T10",   # flake8-debugger
    "I",     # isort
]
ignore = ["S101", "SLF001", "PLR2004", "E501"]
